#!/bin/bash
# Generated by Ridvan Gundogmus - ridvan.gundogmus@botsoftware.com - 2017
# Purpose of this script:
# * Translate gitlog to changelog as a debian package

#generating changelog
usage(){
        echo "Usage 1: ./changeloggit [DIRECTORY]"
        exit 1
}
function creategitchangelog {
	line=`git --no-pager log -n 1 --graph --pretty=format:'%h%x09%an: %s - %d %cr' --abbrev-commit --date=relative`
	dch -i "$line"
	exit 0
}

if [ -z "$1" ];
  then
    usage
else
        cd $1
#changelog file

        if [ ! -f "debian/changelog" ]; then
                dch --create changelog
                creategitchangelog
        else
                creategitchangelog
        fi


fi

